spring:
  config:
    name: '@project.name@'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:resistence;Mode=Oracle
    username: root
    password: password
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      connectionTimeout: 30000 
      idleTimeout: 10000 
      maxLifetime: 180000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/resistence-changelog-master.xml

logging:
  level:
    root: ERROR
    liquibase : INFO
    br.com.letscode.starwars.resistence: INFO

server:
    port: 8080

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  web:
    open-api:
      title: '@project.name@'
      version: '@project.version@'
      description: '@project.description@'

info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'